# Generated by Django 5.0.6 on 2026-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('profissional', 'Profissional de TI'), ('estudante', 'Estudante de TI / Área afim'), ('publico', 'Público Geral')], max_length=20, verbose_name='Perfil do respondente')),
                ('faixa_etaria', models.CharField(choices=[('ate18', 'Até 18 anos'), ('19_24', '19 – 24 anos'), ('25_34', '25 – 34 anos'), ('35_44', '35 – 44 anos'), ('45mais', '45 anos ou mais')], max_length=10, verbose_name='Faixa etária')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('prefiro_nao', 'Prefiro não informar')], max_length=20, verbose_name='Gênero')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior_inc', 'Superior Incompleto'), ('superior_comp', 'Superior Completo'), ('pos', 'Pós-graduação / Mestrado / Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('area_atuacao', models.CharField(choices=[('desenvolvimento', 'Desenvolvimento de Software'), ('infra', 'Infraestrutura / Redes'), ('dados', 'Ciência de Dados / BI'), ('seguranca', 'Segurança da Informação'), ('suporte', 'Suporte Técnico'), ('gestao', 'Gestão de TI'), ('ia', 'Inteligência Artificial'), ('outro', 'Outra'), ('nenhuma', 'Não atuo na área')], max_length=30, verbose_name='Área de atuação em TI')),
                ('tempo_atuacao', models.CharField(choices=[('nenhum', 'Não atuo'), ('menos1', 'Menos de 1 ano'), ('1_3', '1 – 3 anos'), ('4_7', '4 – 7 anos'), ('8mais', '8 anos ou mais')], max_length=10, verbose_name='Tempo de atuação na área')),
                ('percebe_mercado', models.CharField(choices=[('muito_aquecido', 'Muito aquecido'), ('aquecido', 'Aquecido'), ('estavel', 'Estável'), ('desaquecido', 'Desaquecido'), ('nao_sei', 'Não sei avaliar')], max_length=20, verbose_name='Como percebe o mercado de TI atualmente')),
                ('atualizacao_constante', models.BooleanField(default=True, verbose_name='Acredita que atualização constante é necessária?')),
                ('competencias_tecnicas', models.TextField(blank=True, help_text='Separadas por vírgula (preenchido automaticamente pelo form)', verbose_name='Competências técnicas mais valorizadas')),
                ('competencias_comportamentais', models.TextField(blank=True, verbose_name='Competências comportamentais mais valorizadas')),
                ('maior_dificuldade', models.TextField(blank=True, verbose_name='Qual a maior dificuldade para ingressar na área de TI?')),
                ('conselho_iniciante', models.TextField(blank=True, verbose_name='Que conselho daria a quem está iniciando na Computação?')),
                ('percepcao_profissao', models.TextField(blank=True, verbose_name='Como a sociedade percebe os profissionais de TI na sua opinião?')),
                ('desafios_formacao', models.TextField(blank=True, verbose_name='Quais os principais desafios da formação acadêmica em Computação?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
