# Generated by Django 5.0.6 on 2026-06-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('profissional', 'Profissional de TI'), ('estudante', 'Estudante de TI / Área afim'), ('publico', 'Público Geral')], default='estudante', editable=False, max_length=20)),
                ('faixa_etaria', models.CharField(choices=[('ate18', 'Até 18 anos'), ('19_24', '19 – 24 anos'), ('25_34', '25 – 34 anos'), ('35_44', '35 – 44 anos'), ('45mais', '45 anos ou mais')], max_length=10, verbose_name='Faixa etária')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('prefiro_nao', 'Prefiro não informar')], max_length=20, verbose_name='Gênero')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior_inc', 'Superior Incompleto'), ('superior_comp', 'Superior Completo'), ('pos', 'Pós-graduação / Mestrado / Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('percebe_mercado', models.CharField(choices=[('muito_aquecido', 'Muito aquecido'), ('aquecido', 'Aquecido'), ('estavel', 'Estável'), ('desaquecido', 'Desaquecido'), ('nao_sei', 'Não sei avaliar')], max_length=20, verbose_name='Como percebe o mercado de TI atualmente')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('instituicao', models.CharField(max_length=150, verbose_name='Instituição de ensino')),
                ('semestre', models.CharField(choices=[('1', '1º semestre'), ('2', '2º semestre'), ('3', '3º semestre'), ('4', '4º semestre'), ('5', '5º semestre'), ('6', '6º semestre'), ('7', '7º semestre'), ('8', '8º semestre'), ('9', '9º semestre'), ('10', '10º semestre')], max_length=5, verbose_name='Semestre atual')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('ead', 'EAD')], max_length=10, verbose_name='Turno')),
                ('motivo_escolha', models.CharField(choices=[('mercado', 'Mercado de trabalho aquecido'), ('vocacao', 'Vocação / paixão pela área'), ('salario', 'Salário atrativo'), ('influencia', 'Influência de familiares/amigos'), ('outro', 'Outro')], max_length=20, verbose_name='Motivo da escolha do curso')),
                ('possui_estagio', models.BooleanField(default=False, verbose_name='Possui ou já teve estágio na área?')),
                ('competencias_tecnicas', models.TextField(blank=True, verbose_name='Competências técnicas que considera mais importantes')),
                ('competencias_comportamentais', models.TextField(blank=True, verbose_name='Competências comportamentais mais importantes')),
                ('dificuldade_academica', models.TextField(blank=True, verbose_name='Principal dificuldade na graduação')),
                ('expectativa_carreira', models.TextField(blank=True, verbose_name='Quais suas expectativas para a carreira?')),
                ('conselho_iniciante', models.TextField(blank=True, verbose_name='Que conselho daria a quem quer entrar na área?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta – Estudante',
                'verbose_name_plural': 'Respostas – Estudantes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('profissional', 'Profissional de TI'), ('estudante', 'Estudante de TI / Área afim'), ('publico', 'Público Geral')], default='profissional', editable=False, max_length=20)),
                ('faixa_etaria', models.CharField(choices=[('ate18', 'Até 18 anos'), ('19_24', '19 – 24 anos'), ('25_34', '25 – 34 anos'), ('35_44', '35 – 44 anos'), ('45mais', '45 anos ou mais')], max_length=10, verbose_name='Faixa etária')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('prefiro_nao', 'Prefiro não informar')], max_length=20, verbose_name='Gênero')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior_inc', 'Superior Incompleto'), ('superior_comp', 'Superior Completo'), ('pos', 'Pós-graduação / Mestrado / Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('percebe_mercado', models.CharField(choices=[('muito_aquecido', 'Muito aquecido'), ('aquecido', 'Aquecido'), ('estavel', 'Estável'), ('desaquecido', 'Desaquecido'), ('nao_sei', 'Não sei avaliar')], max_length=20, verbose_name='Como percebe o mercado de TI atualmente')),
                ('area_atuacao', models.CharField(choices=[('desenvolvimento', 'Desenvolvimento de Software'), ('infra', 'Infraestrutura / Redes'), ('dados', 'Ciência de Dados / BI'), ('seguranca', 'Segurança da Informação'), ('suporte', 'Suporte Técnico'), ('gestao', 'Gestão de TI'), ('ia', 'Inteligência Artificial'), ('mobile', 'Desenvolvimento Mobile'), ('outro', 'Outra')], max_length=30, verbose_name='Área de atuação')),
                ('tempo_atuacao', models.CharField(choices=[('menos1', 'Menos de 1 ano'), ('1_3', '1 – 3 anos'), ('4_7', '4 – 7 anos'), ('8mais', '8 anos ou mais')], max_length=10, verbose_name='Tempo de atuação')),
                ('regime_trabalho', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ / Freelancer'), ('servidor', 'Servidor Público'), ('socio', 'Sócio / Empreendedor'), ('outro', 'Outro')], max_length=20, verbose_name='Regime de trabalho')),
                ('trabalha_remoto', models.BooleanField(default=False, verbose_name='Trabalha remotamente?')),
                ('atualizacao_constante', models.BooleanField(default=True, verbose_name='Acredita que atualização constante é necessária?')),
                ('competencias_tecnicas', models.TextField(blank=True, verbose_name='Competências técnicas mais valorizadas')),
                ('competencias_comportamentais', models.TextField(blank=True, verbose_name='Competências comportamentais mais valorizadas')),
                ('stack_principal', models.CharField(blank=True, max_length=200, verbose_name='Principal stack/tecnologia que usa')),
                ('maior_dificuldade', models.TextField(blank=True, verbose_name='Maior dificuldade ao ingressar na área')),
                ('conselho_iniciante', models.TextField(blank=True, verbose_name='Conselho para quem está iniciando')),
                ('percepcao_profissao', models.TextField(blank=True, verbose_name='Como a sociedade percebe o profissional de TI?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta – Profissional',
                'verbose_name_plural': 'Respostas – Profissionais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('profissional', 'Profissional de TI'), ('estudante', 'Estudante de TI / Área afim'), ('publico', 'Público Geral')], default='publico', editable=False, max_length=20)),
                ('faixa_etaria', models.CharField(choices=[('ate18', 'Até 18 anos'), ('19_24', '19 – 24 anos'), ('25_34', '25 – 34 anos'), ('35_44', '35 – 44 anos'), ('45mais', '45 anos ou mais')], max_length=10, verbose_name='Faixa etária')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('prefiro_nao', 'Prefiro não informar')], max_length=20, verbose_name='Gênero')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior_inc', 'Superior Incompleto'), ('superior_comp', 'Superior Completo'), ('pos', 'Pós-graduação / Mestrado / Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('percebe_mercado', models.CharField(choices=[('muito_aquecido', 'Muito aquecido'), ('aquecido', 'Aquecido'), ('estavel', 'Estável'), ('desaquecido', 'Desaquecido'), ('nao_sei', 'Não sei avaliar')], max_length=20, verbose_name='Como percebe o mercado de TI atualmente')),
                ('frequencia_uso_tecnologia', models.CharField(choices=[('diario', 'Diariamente'), ('frequente', 'Frequentemente'), ('ocasional', 'Ocasionalmente'), ('raramente', 'Raramente'), ('nunca', 'Nunca')], max_length=15, verbose_name='Com que frequência usa tecnologia digital?')),
                ('confianca_sistemas', models.CharField(choices=[('muita', 'Muita confiança'), ('moderada', 'Confiança moderada'), ('pouca', 'Pouca confiança'), ('nenhuma', 'Nenhuma confiança')], max_length=15, verbose_name='Qual seu nível de confiança em sistemas digitais?')),
                ('associa_ti_a', models.CharField(choices=[('programacao', 'Programação'), ('conserto', 'Conserto de computadores'), ('jogos', 'Desenvolvimento de jogos'), ('redes', 'Redes / Internet'), ('ia', 'Inteligência Artificial'), ('nao_sei', 'Não sei definir')], max_length=20, verbose_name='Quando pensa em TI, o que vem à mente?')),
                ('conhece_profissional_ti', models.BooleanField(default=False, verbose_name='Conhece pessoalmente algum profissional de TI?')),
                ('impacto_ia', models.BooleanField(default=True, verbose_name='Acredita que a IA impactará sua vida nos próximos anos?')),
                ('percepcao_profissao', models.TextField(blank=True, verbose_name='Como você enxerga os profissionais de TI?')),
                ('uso_tecnologia_cotidiano', models.TextField(blank=True, verbose_name='Como a tecnologia está presente no seu dia a dia?')),
                ('preocupacao_digital', models.TextField(blank=True, verbose_name='Tem alguma preocupação com o uso de tecnologia (privacidade, dependência etc.)?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta – Público Geral',
                'verbose_name_plural': 'Respostas – Público Geral',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
